/** Auto-generated from the studio photo library in public/assets/drive. */
export const galleryPhotos: Record<string, string[]> = {
  "Suits": [
    "/assets/drive/suit/suit-1.jpg",
    "/assets/drive/suit/suit-2.jpg",
    "/assets/drive/suit/suit-3.jpg",
    "/assets/drive/suit/suit-4.jpg",
    "/assets/drive/suit/suit-5.jpg",
    "/assets/drive/suit/suit-6v.jpg",
    "/assets/drive/suit/suit-7.jpg",
    "/assets/drive/suit/suit-8.jpg",
    "/assets/drive/suit/suit-9.jpg",
    "/assets/drive/suit/suit-10.jpg",
    "/assets/drive/suit/suit-11.jpg",
    "/assets/drive/suit/suit-12.png",
    "/assets/drive/suit/suit-13.jpg",
    "/assets/drive/suit/suit-14.png",
    "/assets/drive/suit/suit-15.png",
    "/assets/drive/suit/suit-16.png",
    "/assets/drive/suit/suit-17.png",
    "/assets/drive/suit/suit-18.jpg",
    "/assets/drive/suit/suit-19.jpg",
    "/assets/drive/suit/suit-20.jpg",
    "/assets/drive/suit/suit-21.jpg",
    "/assets/drive/suit/suit-22.jpg",
    "/assets/drive/suit/suit-24.jpg",
    "/assets/drive/suit/suit-25.jpg",
    "/assets/drive/suit/suit-26.jpg",
    "/assets/drive/suit/suit-27.jpg",
    "/assets/drive/suit/suit-28.jpg",
    "/assets/drive/suit/suit-29.jpg",
  ],
  "Safari Suits": [
    "/assets/drive/safari-suit/safaari-suit-1.jpg",
    "/assets/drive/safari-suit/safaari-suit-2.jpg",
    "/assets/drive/safari-suit/safaari-suit-3.jpg",
    "/assets/drive/safari-suit/safaari-suit-4.jpg",
    "/assets/drive/safari-suit/safaari-suit-5.jpg",
    "/assets/drive/safari-suit/safaari-suit-6.jpg",
    "/assets/drive/safari-suit/safaari-suit-7.jpg",
    "/assets/drive/safari-suit/safaari-suit-8.jpg",
    "/assets/drive/safari-suit/safaari-suit-9.jpg",
    "/assets/drive/safari-suit/safaari-suit-10.jpg",
    "/assets/drive/safari-suit/safaari-suit-11.jpg",
    "/assets/drive/safari-suit/safaari-suit-12.jpg",
    "/assets/drive/safari-suit/safaari-suit-13.jpg",
    "/assets/drive/safari-suit/safaari-suit-14.jpg",
    "/assets/drive/safari-suit/safaari-suit-15.jpg",
    "/assets/drive/safari-suit/safaari-suit-16.jpg",
    "/assets/drive/safari-suit/safaari-suit-17.jpg",
    "/assets/drive/safari-suit/safaari-suit-18.jpg",
    "/assets/drive/safari-suit/safaari-suit-19.jpg",
    "/assets/drive/safari-suit/safaari-suit-20.jpg",
  ],
  "Safari Normal": [
    "/assets/drive/safari-normal/safari-normal-1.jpg",
    "/assets/drive/safari-normal/safari-normal-2.jpg",
    "/assets/drive/safari-normal/safari-normal-3.jpg",
    "/assets/drive/safari-normal/safari-normal-4.jpg",
    "/assets/drive/safari-normal/safari-normal-5.jpg",
    "/assets/drive/safari-normal/safari-normal-6.jpg",
    "/assets/drive/safari-normal/safari-normal-7.jpg",
    "/assets/drive/safari-normal/safari-normal-8.jpg",
    "/assets/drive/safari-normal/safari-normal-9.jpg",
    "/assets/drive/safari-normal/safari-normal-10.jpg",
    "/assets/drive/safari-normal/safari-normal-11.jpg",
  ],
  "Shaar": [
    "/assets/drive/shaar/shaar-1.jpg",
    "/assets/drive/shaar/shaar-2.jpg",
    "/assets/drive/shaar/shaar-3.jpg",
    "/assets/drive/shaar/shaar-4.jpg",
    "/assets/drive/shaar/shaar-5.jpg",
    "/assets/drive/shaar/shaar-6.jpg",
    "/assets/drive/shaar/shaar-6-1.jpg",
    "/assets/drive/shaar/shaar-7.jpg",
    "/assets/drive/shaar/shaar-8.jpg",
    "/assets/drive/shaar/shaar-9.jpg",
    "/assets/drive/shaar/shaar-10.jpg",
    "/assets/drive/shaar/shaar-11.jpg",
    "/assets/drive/shaar/shaar-12.jpg",
    "/assets/drive/shaar/shaar-13.jpg",
    "/assets/drive/shaar/shaar-14-1.jpg",
    "/assets/drive/shaar/shaar-14.jpg",
    "/assets/drive/shaar/shaar-15.jpg",
    "/assets/drive/shaar/shaar-16.jpg",
    "/assets/drive/shaar/shaar-17.jpg",
    "/assets/drive/shaar/shaar-18.jpg",
    "/assets/drive/shaar/shaar-19.jpg",
    "/assets/drive/shaar/shaar-20.jpg",
  ],
  "Qamis": [
    "/assets/drive/qamiis/qamiis-1.jpg",
    "/assets/drive/qamiis/qamiis-2.jpg",
    "/assets/drive/qamiis/qamiis-4.jpg",
    "/assets/drive/qamiis/qamiis-5.jpg",
    "/assets/drive/qamiis/qamiis-6.jpg",
    "/assets/drive/qamiis/qamiis-7.jpg",
    "/assets/drive/qamiis/qamiis-8.jpg",
    "/assets/drive/qamiis/qamiis-9.jpg",
    "/assets/drive/qamiis/qamiis-10.jpg",
    "/assets/drive/qamiis/qamiis-11.jpg",
    "/assets/drive/qamiis/qamiis-12.jpg",
    "/assets/drive/qamiis/qamiis-13.jpg",
  ],
  "Surwaal": [
    "/assets/drive/surwaal/surwaal-1.jpg",
    "/assets/drive/surwaal/surwaal-2.jpg",
    "/assets/drive/surwaal/surwaal-3.jpg",
    "/assets/drive/surwaal/surwaal-4.jpg",
    "/assets/drive/surwaal/surwaal-5.jpg",
    "/assets/drive/surwaal/surwaal-6.jpg",
    "/assets/drive/surwaal/surwaal-7.jpg",
    "/assets/drive/surwaal/surwaal-8.jpg",
    "/assets/drive/surwaal/surwaal-9.jpg",
    "/assets/drive/surwaal/surwaal-10.jpg",
    "/assets/drive/surwaal/surwaal-11.jpg",
    "/assets/drive/surwaal/surwaal-12.jpg",
    "/assets/drive/surwaal/surwaal-13.jpg",
    "/assets/drive/surwaal/surwaal-15.jpg",
  ],
};

export const serviceImages = {
  "Suits": "/assets/drive/suit/suit-service.jpg",
  "Safari Suits": "/assets/drive/safari-suit/safaari-suit-service.jpg",
  "Safari Normal": "/assets/drive/safari-normal/safari-normal-service.jpg",
  "Shaar": "/assets/drive/shaar/shaar-service.jpg",
  "Qamis": "/assets/drive/qamiis/qamiis-service.jpg",
  "Surwaal": "/assets/drive/surwaal/surwaal-service.jpg",
} as const;
